# Generated by Django 2.1.7 on 2019-03-21 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20190320_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='completname',
            field=models.CharField(default='Default Value', max_length=60),
        ),
    ]
