# Generated by Django 2.1.7 on 2019-03-21 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_author_completname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='completname',
            field=models.CharField(default='', max_length=60),
        ),
    ]
